# Generated by Django 6.0.3 on 2026-03-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('specialization', models.TextField()),
                ('achievements', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
            },
        ),
    ]
