# Generated by Django 6.0.3 on 2026-03-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_coach_created_at_coach_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
